<a href="https://colab.research.google.com/github/AlirezaAhadipour/PyTorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import numpy as np
print(torch.__version__)

2.2.1+cu121


### Introduction to tensors

In [16]:
## Scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

6

In [15]:
## Vector
vector = torch.tensor([6, 7])
vector

tensor([6, 7])

In [9]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [18]:
## MATRIX
MATRIX = torch.tensor([[6, 7], [8, 9]])
MATRIX

tensor([[6, 7],
        [8, 9]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([6, 7])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
## TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

In [28]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [29]:
# Create a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2237, 0.3909, 0.8203, 0.1041],
        [0.0801, 0.3595, 0.9668, 0.9462],
        [0.2420, 0.5170, 0.9425, 0.6402]])

In [31]:
random_tensor.ndim

2

In [36]:
# Create a random tensor with an image shape
random_image_size_tensor = torch.rand(size=(3, 224, 224))   # color channels, height, weight
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros & Ones

In [38]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

### Create a range of tensors

In [41]:
torch.range(0, 10)

<ipython-input-41-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
sample = torch.arange(start=1, end=100, step=13)
sample

tensor([ 1, 14, 27, 40, 53, 66, 79, 92])

In [45]:
# tensor-like
zeros = torch.zeros_like(input=sample)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [48]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [49]:
float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [54]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,   # what datatype is the tensor (e.g. float32 or float16)
                               device=None,   # what device is tensor on (e.g. "cpu", "cuda")
                               requires_grad=False)   # whether or not to track gradients with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [57]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [58]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [59]:
int_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [60]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Tensors attributes

In [61]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0931, 0.0789, 0.9686, 0.9950],
        [0.1747, 0.3945, 0.3605, 0.8559],
        [0.3283, 0.1310, 0.9689, 0.1766]])

In [62]:
print(f'Datatype = {some_tensor.dtype}')
print(f'Shape = {some_tensor.shape}')
print(f'Device = {some_tensor.device}')

Datatype = torch.float32
Shape = torch.Size([3, 4])
Device = cpu


### Manipulating tensors (tensor operations)

In [63]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [71]:
# addition
print(tensor + 10)
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [72]:
# multiplication
print(tensor * 10)
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [73]:
# subtraction
print(tensor - 10)
print(torch.sub(tensor, 10))

tensor([-9, -8, -7])
tensor([-9, -8, -7])


In [75]:
# division
print(tensor / 10)
print(torch.div(tensor, 10))

tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])


In [81]:
# matrix multiplication
print(tensor @ tensor)
print(torch.matmul(tensor, tensor))

tensor(14)
tensor(14)


In [83]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.8332, 0.8596, 0.7732],
        [0.2671, 0.0224, 0.2720],
        [1.0547, 0.6521, 1.0204]])

In [89]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[9, 8], [7, 6], [5, 4]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[25, 19, 13],
        [59, 45, 31],
        [93, 71, 49]])

### Tensor aggregation

In [103]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [104]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [105]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [106]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [107]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [108]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [109]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [112]:
## Reshaping, viewing, stacking, squeezing, unsqueezing

In [120]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [121]:
# Reshape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [122]:
# View
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [123]:
# view of a tensor shares the same memory as the original tensor, so changing z changes x
z[:, 0] = -99
z, x

(tensor([[-99,   2,   3,   4,   5,   6,   7,   8,   9]]),
 tensor([-99,   2,   3,   4,   5,   6,   7,   8,   9]))

In [124]:
# Stack
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[-99,   2,   3,   4,   5,   6,   7,   8,   9],
        [-99,   2,   3,   4,   5,   6,   7,   8,   9],
        [-99,   2,   3,   4,   5,   6,   7,   8,   9]])

In [125]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[-99, -99, -99],
        [  2,   2,   2],
        [  3,   3,   3],
        [  4,   4,   4],
        [  5,   5,   5],
        [  6,   6,   6],
        [  7,   7,   7],
        [  8,   8,   8],
        [  9,   9,   9]])

In [133]:
# Squeez
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([-99,   2,   3,   4,   5,   6,   7,   8,   9]), torch.Size([9]))

In [131]:
x_reshaped, x_reshaped.shape

(tensor([[-99,   2,   3,   4,   5,   6,   7,   8,   9]]), torch.Size([1, 9]))

In [135]:
# Unsqueez
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[-99,   2,   3,   4,   5,   6,   7,   8,   9]]), torch.Size([1, 9]))

In [136]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[-99],
         [  2],
         [  3],
         [  4],
         [  5],
         [  6],
         [  7],
         [  8],
         [  9]]),
 torch.Size([9, 1]))

In [138]:
# Permute
x = torch.rand(2, 3, 5)
x, x.shape

(tensor([[[0.5485, 0.2416, 0.4239, 0.3157, 0.8808],
          [0.5027, 0.8535, 0.1386, 0.4975, 0.5468],
          [0.3504, 0.4445, 0.8390, 0.0101, 0.2866]],
 
         [[0.7875, 0.2450, 0.1266, 0.6658, 0.8790],
          [0.3029, 0.4830, 0.7477, 0.6650, 0.3005],
          [0.6220, 0.9788, 0.2944, 0.2380, 0.8714]]]),
 torch.Size([2, 3, 5]))

In [139]:
x_permuted = torch.permute(x, (2, 0, 1))
x_permuted, x_permuted.shape

(tensor([[[0.5485, 0.5027, 0.3504],
          [0.7875, 0.3029, 0.6220]],
 
         [[0.2416, 0.8535, 0.4445],
          [0.2450, 0.4830, 0.9788]],
 
         [[0.4239, 0.1386, 0.8390],
          [0.1266, 0.7477, 0.2944]],
 
         [[0.3157, 0.4975, 0.0101],
          [0.6658, 0.6650, 0.2380]],
 
         [[0.8808, 0.5468, 0.2866],
          [0.8790, 0.3005, 0.8714]]]),
 torch.Size([5, 2, 3]))

### Indexing

In [140]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [141]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [143]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [145]:
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [146]:
x[:, 0]

tensor([[1, 2, 3]])

In [147]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [148]:
### PyTorch tensors & NumPy

In [154]:
# NumPy array to tensor
array = np.arange(1, 10)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [155]:
array.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [156]:
array += 1
array, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [163]:
# Tensor to NumPy array
tensor = torch.arange(1, 10)
array = tensor.numpy()
tensor, array

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [164]:
tensor.dtype, array.dtype

(torch.int64, dtype('int64'))

In [165]:
tensor += 1
tensor, array

(tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

### Reproducibility

In [167]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
random_tensor_A, random_tensor_B

(tensor([[0.1897, 0.2168, 0.8015, 0.7582],
         [0.4812, 0.0600, 0.8848, 0.8555],
         [0.6628, 0.5340, 0.8162, 0.6614]]),
 tensor([[0.6467, 0.4562, 0.0746, 0.7967],
         [0.1083, 0.3158, 0.1484, 0.4289],
         [0.2975, 0.7980, 0.0434, 0.1005]]))

In [170]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running on GPUs

In [5]:
!nvidia-smi

Sun Mar 24 21:00:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# Check for access
torch.cuda.is_available()

True

In [3]:
# Setting device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
# Count the number of devices
torch.cuda.device_count()

1

In [6]:
# Put tensor on GPU
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [9]:
# Move tensors to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [12]:
# Move tensors back to CPU
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))