<a href="https://colab.research.google.com/github/AlirezaAhadipour/PyTorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to tensors

In [16]:
## Scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

6

In [15]:
## Vector
vector = torch.tensor([6, 7])
vector

tensor([6, 7])

In [9]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [18]:
## MATRIX
MATRIX = torch.tensor([[6, 7], [8, 9]])
MATRIX

tensor([[6, 7],
        [8, 9]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([6, 7])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
## TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

In [28]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [29]:
# Create a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2237, 0.3909, 0.8203, 0.1041],
        [0.0801, 0.3595, 0.9668, 0.9462],
        [0.2420, 0.5170, 0.9425, 0.6402]])

In [31]:
random_tensor.ndim

2

In [36]:
# Create a random tensor with an image shape
random_image_size_tensor = torch.rand(size=(3, 224, 224))   # color channels, height, weight
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros & Ones

In [38]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32